
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="container mx-auto py-12">
      <Card className="max-w-3xl mx-auto shadow-xl">
        <CardHeader>
          <CardTitle className="text-3xl font-bold font-headline">Terms and Conditions</CardTitle>
          <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 prose dark:prose-invert max-w-none">
          <p>Welcome to DhirPrint AI! These terms and conditions outline the rules and regulations for the use of DhirPrint AI&apos;s Website.</p>

          <p>By accessing this website we assume you accept these terms and conditions. Do not continue to use DhirPrint AI if you do not agree to take all of the terms and conditions stated on this page.</p>

          <h2 className="font-semibold text-xl">1. Definitions</h2>
          <p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: &quot;Client&quot;, &quot;You&quot; and &quot;Your&quot; refers to you, the person log on this website and compliant to the Company’s terms and conditions. &quot;The Company&quot;, &quot;Ourselves&quot;, &quot;We&quot;, &quot;Our&quot; and &quot;Us&quot;, refers to our Company. &quot;Party&quot;, &quot;Parties&quot;, or &quot;Us&quot;, refers to both the Client and ourselves. </p>
          
          <h2 className="font-semibold text-xl">2. Use of the Website</h2>
          <p>You are granted a non-exclusive, non-transferable, revocable license to access and use DhirPrint AI strictly in accordance with these terms of use. As a condition of your use of the Site, you warrant to DhirPrint AI that you will not use the Site for any purpose that is unlawful or prohibited by these Terms.</p>

          <h2 className="font-semibold text-xl">3. Intellectual Property Rights</h2>
          <p>Other than the content you own, under these Terms, DhirPrint AI and/or its licensors own all the intellectual property rights and materials contained in this Website. You are granted limited license only for purposes of viewing the material contained on this Website.</p>
          <p>Designs generated by users through the AI tool remain the intellectual property of the user, however, DhirPrint AI is granted a license to use these designs for the purpose of fulfilling the order and for promotional materials with user consent.</p>

          <h2 className="font-semibold text-xl">4. Products and Services</h2>
          <p>All products are subject to availability, and we reserve the right to impose quantity limits on any order, to reject all or part of an order, and to discontinue products without notice, even if you have already placed your order.</p>
          <p>Prices for our products are subject to change without notice. We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.</p>

          <h2 className="font-semibold text-xl">5. User Accounts</h2>
          <p>If you create an account on the Website, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it.</p>
          
          <h2 className="font-semibold text-xl">6. Limitation of Liability</h2>
          <p>In no event shall DhirPrint AI, nor any of its officers, directors and employees, be held liable for anything arising out of or in any way connected with your use of this Website whether such liability is under contract. DhirPrint AI, including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.</p>

          <h2 className="font-semibold text-xl">7. Governing Law & Jurisdiction</h2>
          <p>These Terms will be governed by and interpreted in accordance with the laws of the jurisdiction in which DhirPrint AI is located, and you submit to the non-exclusive jurisdiction of the state and federal courts located in that jurisdiction for the resolution of any disputes.</p>

          <p><em>This is a sample terms and conditions page. You should consult with a legal professional to create terms and conditions specific to your business and jurisdiction.</em></p>
        </CardContent>
      </Card>
    </div>
  );
}
